### ISSUE TITLE
Error running the Demo

### ISSUE THREAD

**Issue by samuel-cerezo** [cvg/nicer-slam#10]
Hi,

When i followed the steps for running the demo, i obtained 

```
Traceback (most recent call last):
  File "visualizer.py", line 34, in <module>
    scalemat = np.load(f'Datasets/processed/Replica/scan{scanid}/cameras.npz')['scale_mat_0']
  File "/home/samuel/anaconda3/envs/nicer-slam/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'Datasets/processed/Replica/scan3/cameras.npz'
```

Can you help me please?

Thanks!

**Comment by OnHaDe** [comment]
Looks like you are using the wrong configuration.

**Comment by YerldSHO** [comment]
I also faced this problem. Haven't found a solution yet

**Comment by YerldSHO** [comment]
Where is Datasets/processed/Replica/scan{scanid}/cameras.npz? The error is that the file does not exist at the specified path

**Comment by samuel-cerezo** [comment]
Exactly, the file is missing

**Comment by OnHaDe** [comment]
~~What are the steps you followed?
Demo 1 and 2 use `/Datasets/processed/Demo` as their data path.
The fact that you get the `Replica` path in your Error suggests the wrong config file~~

Call the visualizer script with `--output "path"`
The path needs to contain the word 'demo'
This is because of:
https://github.com/cvg/nicer-slam/blob/main/visualizer.py#L47-L49

**Comment by YerldSHO** [comment]
It's not entirely clear what you meant.

bash scripts/download_vis_replica_room2.sh
OUTPUT_FOLDER=exps/replica_3/2024_02_27_00_12_45sample_vis
python visualizer.py --output $OUTPUT_FOLDER

your example -> 
bash scripts/download_vis_replica_room2.sh
OUTPUT_FOLDER=exps/replica_3/2024_02_27_00_12_45sample_vis replica
python visualizer.py --output $OUTPUT_FOLDER ???

**Comment by OnHaDe** [comment]
I answered under the assumption you are trying to run the demo and not the Replica dataset.
The Replica Dataset requires you to run the preprocessing first, which creates the `camera.npz` file (Unless the Replica dataset comes with one in which case you manually have to move it into the correct directory). I don't know why that is not pointed out except for the "Run" section of the Readme

**Comment by Zzh2000** [comment]
You are right, cameras.npz is generated during the Replica dataset preprocessing, when running Demo many users will not have this file. I will later directly provide a cameras.npz for demo. Sorry for this confusion.
